### ISSUE TITLE
Doesn't meet 1.1.0 > 1.1.0-beta

### ISSUE THREAD

**Issue by chandrush** [Ruhrpottpatriot/SemanticVersion#10]
This test is not passing.

SemanticVersion left = new SemanticVersion(1, 1, 0);
SemanticVersion right = new SemanticVersion(1, 1, 0, "beta");
VersionComparer comparer = new VersionComparer();
Assert.Equal(1, comparer.Compare(left, right));

**Comment by DannyMeister** [comment]
Will there be a release soon incorporating the pull request which fixes this bug?  The entire reason I wanted to use this library is to compare pre-release and release versions.

**Comment by Ruhrpottpatriot** [comment]
@chandrush @DannyMeister Pull request #11 has been merged
