### ISSUE TITLE
Target Version 4.5

### ISSUE THREAD

**Issue by SchreinerK** [Ruhrpottpatriot/SemanticVersion#12]
Could not install package 'SemanticVersion 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by Ruhrpottpatriot** [comment]
This assembly requires at least netstandard1.2, which translates to .NET 4.5.1 at minimum. See [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) for more details on netstandard
