### ISSUE TITLE
Version Parse does not support suffix after a dot

### ISSUE THREAD

**Issue by OrShamirCM** [Ruhrpottpatriot/SemanticVersion#17]
Enable  suffix after a dot ( 1.2.3.Final )

suggested updated REGEX - 
`/^(?<major>[0]|[1-9]+[0-9]*|[*])((\.(?<minor>[0]|[1-9]+[0-9]*|[*]))(\.(?<patch>[0]|[1-9]+[0-9]*|[*]))?)?(\-|.(?<pre>[0-9A-Za-z\-\.]+|[*]))?(\+(?<build>[0-9A-Za-z\-\.]+|[*]))?$/gm`

I added . for group 7 (instead of just - )

**Comment by Ruhrpottpatriot** [comment]
This is **not** a valid SemanticVersion. Pre-release identifiers MUST be separated by a hypen ("-"), and build metadata MUST be separated by a plus ("+") as by the [SemVer spec](https://semver.org/) (see the BNF).

As of now SemVer doesn't have provisions for "Final" versions and a final version would simply be the highest version available. Though I'd argue that, even though it's a bit iffy at best and wrong at worst, you could use the _build metadata_ field for that. So, the correct style for the version you wrote would be: 1.2.3+Final
