### ISSUE TITLE
Exception-less TryParse

### ISSUE THREAD

**Issue by kostrse** [Ruhrpottpatriot/SemanticVersion#3]
Hi Robert, thanks for the great library!

Was looking at the code and wanted to suggest a minor enhancement:

Due to handling of thrown exceptions adds extra overhead, for better performance it's better to have the main parsing logic in `SemanticVersion.TryParse(...)`, without throwing any exceptions. And have lightweight implementation of the `SemanticVersion.Parse(...)` that wraps around the `TryParse` and throws exception on _false_.

**Comment by Ruhrpottpatriot** [comment]
Thanks for the suggestion!

Change was done in c75e1f7a53f01503c9a915d24d9d3b30e2d818eb
