### ISSUE TITLE
Create a Version with a Strong Name as Well

### ISSUE THREAD

**Issue by montanehamilton** [Ruhrpottpatriot/SemanticVersion#9]
A signed version would be helpful.

**Comment by brandonprudent** [comment]
Why was this closed? It looks like the issue persists

**Comment by Ruhrpottpatriot** [comment]
@montanehamilton @brandonprudent Sorry for the delay, but 362f5dd6a0e74bb845d4869406af8a191d34635e adds strong naming. Does this suffice for you two?
